#!/usr/bin/env php
<?php

declare(strict_types=1);

/*
 * UserFrosting CRUD6 Sprinkle Integration Test - Path Testing Script
 *
 * This script tests API and frontend paths from a JSON configuration file.
 * It's designed to be modular and reusable across different sprinkles.
 *
 * Usage: php test-paths.php <config_file> [auth|unauth|both] [api|frontend|both]
 * Example: php test-paths.php integration-test-paths.json auth api
 * Example: php test-paths.php integration-test-paths.json both both  # Tests both authenticated and unauthenticated
 */

// Configuration constants
const DEFAULT_PLAYWRIGHT_STATE_FILE = '/tmp/admin-auth-state.json';
const MAX_COOKIE_EXPIRE_TIMESTAMP = 253402300799;  // Year 9999-12-31 23:59:59 UTC

// Parse command line arguments
$configFile = $argv[1] ?? null;
$authType = $argv[2] ?? 'both';  // auth, unauth, or both
$pathType = $argv[3] ?? 'both';  // api, frontend, or both
// Optional: Playwright storageState file (check env var first, then arg, then default)
$playwrightStateFile = $argv[4] ?? getenv('PLAYWRIGHT_STATE_FILE') ?: DEFAULT_PLAYWRIGHT_STATE_FILE;

if (!$configFile) {
    echo "Usage: php test-paths.php <config_file> [auth|unauth|both] [api|frontend|both] [playwright_state_file]\n";
    echo "Example: php test-paths.php integration-test-paths.json auth api\n";
    echo "Example: php test-paths.php integration-test-paths.json auth api /tmp/admin-auth-state.json\n";
    exit(1);
}

// Load configuration
if (!file_exists($configFile)) {
    echo "ERROR: Configuration file not found: {$configFile}\n";
    exit(1);
}

$config = json_decode(file_get_contents($configFile), true);
if (!$config) {
    echo "ERROR: Failed to parse configuration file\n";
    exit(1);
}

$baseUrl = $config['config']['base_url'] ?? 'http://localhost:8080';
$username = $config['config']['auth']['username'] ?? 'admin';
$password = $config['config']['auth']['password'] ?? 'admin123';

echo "=========================================\n";
echo "Testing Paths from Configuration\n";
echo "=========================================\n";
echo "Config file: {$configFile}\n";
echo "Base URL: {$baseUrl}\n";
echo "Auth type: {$authType}\n";
echo "Path type: {$pathType}\n";
if (file_exists($playwrightStateFile)) {
    echo "Playwright state: {$playwrightStateFile} (found)\n";
} else {
    echo "Playwright state: {$playwrightStateFile} (not found, will use curl login)\n";
}
echo "\n";

$totalTests = 0;
$passedTests = 0;
$failedTests = 0;
$skippedTests = 0;
$warningTests = 0;

// Global cookie jar for session management
$cookieJar = tempnam(sys_get_temp_dir(), 'cookies_');

/**
 * Convert Playwright storageState JSON to curl cookie jar format
 * 
 * @param string $playwrightStateFile Path to Playwright storageState.json file
 * @param string $cookieJar Path to curl cookie jar file to create
 * @return bool True if conversion successful, false otherwise
 */
function convertPlaywrightToCurlCookies($playwrightStateFile, $cookieJar) {
    if (!file_exists($playwrightStateFile)) {
        echo "⚠️  Playwright state file not found: {$playwrightStateFile}\n";
        return false;
    }
    
    $stateContent = file_get_contents($playwrightStateFile);
    if ($stateContent === false) {
        echo "⚠️  Failed to read Playwright state file\n";
        return false;
    }
    
    $state = json_decode($stateContent, true);
    if (json_last_error() !== JSON_ERROR_NONE) {
        echo "⚠️  Invalid JSON in Playwright state file: " . json_last_error_msg() . "\n";
        return false;
    }
    
    if (!$state || !isset($state['cookies'])) {
        echo "⚠️  Playwright state file missing 'cookies' key\n";
        return false;
    }
    
    // Netscape cookie jar format header
    $cookieJarContent = "# Netscape HTTP Cookie File\n";
    $cookieJarContent .= "# This file was generated by test-paths.php from Playwright storageState\n";
    $cookieJarContent .= "# Edit at your own risk.\n\n";
    
    foreach ($state['cookies'] as $cookie) {
        // Netscape cookie jar format:
        // domain flag path secure expiration name value
        $domain = $cookie['domain'] ?? 'localhost';
        
        // Domain flag: TRUE if domain starts with '.' (applies to all subdomains), FALSE otherwise
        // Example: '.example.com' matches example.com and www.example.com (flag=TRUE)
        //          'localhost' matches only localhost (flag=FALSE)
        $flag = (strpos($domain, '.') === 0) ? 'TRUE' : 'FALSE';
        
        $path = $cookie['path'] ?? '/';
        $secure = ($cookie['secure'] ?? false) ? 'TRUE' : 'FALSE';
        
        // Convert expires: -1 means session cookie, use far future date
        $expires = $cookie['expires'] ?? -1;
        if ($expires === -1) {
            // Use PHP_INT_MAX for better compatibility (works on both 32-bit and 64-bit systems)
            // Falls back to year 2038 max on 32-bit systems, much further on 64-bit
            $expires = min(PHP_INT_MAX, MAX_COOKIE_EXPIRE_TIMESTAMP);
        } else {
            $expires = (int) $expires;
        }
        
        $name = $cookie['name'] ?? '';
        $value = $cookie['value'] ?? '';
        
        // Skip empty cookies
        if (empty($name)) {
            continue;
        }
        
        $cookieJarContent .= "{$domain}\t{$flag}\t{$path}\t{$secure}\t{$expires}\t{$name}\t{$value}\n";
    }
    
    $result = file_put_contents($cookieJar, $cookieJarContent);
    if ($result === false) {
        echo "⚠️  Failed to write cookie jar file: {$cookieJar}\n";
        return false;
    }
    
    return true;
}

/**
 * Perform login to get authenticated session
 * 
 * @param string $baseUrl Base URL of the application
 * @param string $username Username to login with
 * @param string $password Password to login with
 * @param string $cookieJar Path to cookie jar file
 * @return bool True if login successful, false otherwise
 */
function performLogin($baseUrl, $username, $password, $cookieJar) {
    echo "=========================================\n";
    echo "Authenticating User\n";
    echo "=========================================\n";
    echo "Username: {$username}\n";
    echo "Login URL: {$baseUrl}/account/sign-in\n\n";
    
    // Step 1: Get the login page to obtain CSRF token and initial session
    $loginPageUrl = $baseUrl . '/account/sign-in';
    $tmpFile = tempnam(sys_get_temp_dir(), 'login_page_');
    
    $curlCmd = "curl -s -o {$tmpFile} -c {$cookieJar} -L " . escapeshellarg($loginPageUrl) . " 2>&1";
    exec($curlCmd, $output, $returnCode);
    
    if ($returnCode !== 0) {
        echo "❌ Failed to load login page\n";
        echo "   Error: " . implode("\n   ", $output) . "\n\n";
        unlink($tmpFile);
        return false;
    }
    
    $loginPageContent = file_get_contents($tmpFile);
    unlink($tmpFile);
    
    // Extract CSRF token from the login page
    // UserFrosting 6 uses meta tags for CSRF tokens: <meta name="csrf-token" content="...">
    $csrfToken = null;
    
    // Try meta tag first (UserFrosting 6 standard)
    if (preg_match('/<meta[^>]*name=["\']csrf-token["\'][^>]*content=["\']([^"\']+)["\']/', $loginPageContent, $matches)) {
        $csrfToken = $matches[1];
    } elseif (preg_match('/<meta[^>]*content=["\']([^"\']+)["\'][^>]*name=["\']csrf-token["\']/', $loginPageContent, $matches)) {
        $csrfToken = $matches[1];
    }
    // Fallback to input field (older UserFrosting versions)
    elseif (preg_match('/<input[^>]*name=["\']csrf_token["\'][^>]*value=["\']([^"\']+)["\']/', $loginPageContent, $matches)) {
        $csrfToken = $matches[1];
    } elseif (preg_match('/<input[^>]*value=["\']([^"\']+)["\'][^>]*name=["\']csrf_token["\']/', $loginPageContent, $matches)) {
        $csrfToken = $matches[1];
    } elseif (preg_match('/name="csrf_token"\s+value="([^"]+)"/', $loginPageContent, $matches)) {
        $csrfToken = $matches[1];
    }
    
    if (!$csrfToken) {
        echo "⚠️  Warning: Could not extract CSRF token from login page\n";
        echo "   Checked for both meta tag (<meta name=\"csrf-token\">) and input field patterns\n";
        echo "   Attempting login without CSRF token...\n";
        
        // Debug: Save login page content for inspection
        $debugFile = tempnam(sys_get_temp_dir(), 'login_page_debug_');
        file_put_contents($debugFile, $loginPageContent);
        echo "   Debug: Login page content saved to {$debugFile}\n";
    } else {
        echo "✅ CSRF token obtained: " . substr($csrfToken, 0, 20) . "...\n";
    }
    
    // Step 2: Submit login form
    $loginUrl = $baseUrl . '/account/sign-in';
    $tmpFile = tempnam(sys_get_temp_dir(), 'login_response_');
    
    // Build form data
    $postData = [
        'user_name' => $username,
        'password' => $password,
    ];
    
    // UserFrosting 6 expects CSRF token in both X-CSRF-Token header and form data
    if ($csrfToken) {
        $postData['csrf_token'] = $csrfToken;
    }
    
    // Convert to URL-encoded string
    $postDataString = http_build_query($postData);
    
    // Perform login POST request with CSRF token in header
    $curlCmd = "curl -s -o {$tmpFile} -w '%{http_code}' -b {$cookieJar} -c {$cookieJar} -L " .
               "-X POST -H 'Content-Type: application/x-www-form-urlencoded' ";
    
    // Add X-CSRF-Token header if available (UserFrosting 6 standard)
    // Note: escapeshellarg() adds its own quotes, so we use -H format without wrapping quotes
    if ($csrfToken) {
        $curlCmd .= "-H " . escapeshellarg("X-CSRF-Token: " . $csrfToken) . " ";
    }
    
    $curlCmd .= "--data " . escapeshellarg($postDataString) . " " . escapeshellarg($loginUrl) . " 2>&1";
    
    $httpCode = trim(shell_exec($curlCmd));
    $loginResponse = file_get_contents($tmpFile);
    unlink($tmpFile);
    
    // Check if login was successful
    // Successful login typically results in redirect (302/303) or 200
    // We check for absence of login form and presence of dashboard/logged-in indicators
    $isStillOnLoginPage = (
        strpos($loginResponse, 'sign-in') !== false ||
        strpos($loginResponse, 'data-test="username"') !== false ||
        strpos($loginResponse, 'Please sign in') !== false
    );
    
    $hasLoggedInIndicators = (
        strpos($loginResponse, 'dashboard') !== false ||
        strpos($loginResponse, 'sign-out') !== false ||
        strpos($loginResponse, 'Sign Out') !== false ||
        strpos($loginResponse, 'logout') !== false
    );
    
    if ($hasLoggedInIndicators && !$isStillOnLoginPage) {
        echo "✅ Login successful (HTTP {$httpCode})\n";
        echo "   Session established\n\n";
        return true;
    } else {
        echo "❌ Login failed (HTTP {$httpCode})\n";
        if ($isStillOnLoginPage) {
            echo "   Still on login page - credentials may be incorrect\n";
        }
        echo "   Response length: " . strlen($loginResponse) . " bytes\n";
        
        // Check for specific error messages in the response (case-insensitive)
        if (stripos($loginResponse, 'CSRF') !== false) {
            echo "   ⚠️  Response contains CSRF-related content\n";
        }
        if (stripos($loginResponse, 'Invalid') !== false) {
            echo "   ⚠️  Response contains 'Invalid' message\n";
        }
        if (stripos($loginResponse, 'error') !== false) {
            echo "   ⚠️  Response contains error message\n";
        }
        
        // Debug: Save login response for inspection
        $debugFile = tempnam(sys_get_temp_dir(), 'login_response_debug_');
        file_put_contents($debugFile, $loginResponse);
        echo "   Debug: Login response saved to {$debugFile}\n\n";
        return false;
    }
}

// Function to test a path
function testPath($name, $pathConfig, $baseUrl, $isAuth = false, $username = null, $password = null, $cookieJar = null) {
    global $totalTests, $passedTests, $failedTests, $skippedTests, $warningTests;
    
    $totalTests++;
    
    // Check if test should be skipped
    if (isset($pathConfig['skip']) && $pathConfig['skip']) {
        echo "⏭️  SKIP: {$name}\n";
        echo "   Reason: " . ($pathConfig['skip_reason'] ?? 'Not specified') . "\n\n";
        $skippedTests++;
        return;
    }
    
    $path = $pathConfig['path'];
    $method = $pathConfig['method'] ?? 'GET';
    $description = $pathConfig['description'] ?? $name;
    $expectedStatus = $pathConfig['expected_status'] ?? 200;
    
    echo "Testing: {$name}\n";
    echo "   Description: {$description}\n";
    echo "   Method: {$method}\n";
    echo "   Path: {$path}\n";
    
    // Build curl command
    $url = $baseUrl . $path;
    $tmpFile = tempnam(sys_get_temp_dir(), 'path_test_');
    
    // Basic curl options
    $curlCmd = "curl -s -o {$tmpFile} -w '%{http_code}' ";
    
    // Add authentication cookie jar if needed
    if ($isAuth && $cookieJar && file_exists($cookieJar)) {
        // Use cookie jar for authenticated requests
        $curlCmd .= "-b {$cookieJar} -c {$cookieJar} ";
    }
    
    // Follow redirects
    $curlCmd .= "-L ";
    
    // Add payload for POST/PUT/PATCH requests
    if (isset($pathConfig['payload']) && in_array($method, ['POST', 'PUT', 'PATCH'])) {
        $payload = json_encode($pathConfig['payload']);
        $curlCmd .= "-H 'Content-Type: application/json' --data " . escapeshellarg($payload) . " ";
    }
    
    $curlCmd .= "-X " . escapeshellarg($method) . " " . escapeshellarg($url);
    
    // Execute curl command
    $httpCode = trim(shell_exec($curlCmd));
    
    // For unauthenticated API tests, permission failures (400/401/403) should warn, not fail
    // We're looking for actual code/SQL failures (500, syntax errors, etc.)
    // Note: Patterns are hardcoded as they're specific to CRUD6 API structure
    $isUnauthApiTest = !$isAuth && isset($pathConfig['path']) && strpos($pathConfig['path'], '/api/') !== false;
    $isPermissionFailure = in_array($httpCode, ['400', '401', '403']); // HTTP bad request/unauthorized/forbidden
    $isServerError = in_array($httpCode, ['500', '502', '503', '504']); // HTTP server errors
    
    // Check if this is a CREATE endpoint (POST method to /api/crud6/{model})
    // Excludes custom actions (/a/{action}) which use POST but aren't create operations
    $isCreateEndpoint = $method === 'POST' && strpos($path, '/api/crud6/') !== false && !strpos($path, '/a/');
    
    // Check if status_any validation allows multiple acceptable status codes
    $acceptableStatuses = null;
    if (isset($pathConfig['validation']) && $pathConfig['validation']['type'] === 'status_any') {
        $acceptableStatuses = $pathConfig['validation']['acceptable_statuses'] ?? [];
    }
    
    // Determine if the status code is acceptable
    // Note: $httpCode is a string from curl, $expectedStatus is typically an int
    $httpCodeInt = (int)$httpCode;
    $expectedStatusInt = (int)$expectedStatus;
    $statusIsAcceptable = ($httpCodeInt === $expectedStatusInt);
    if (!$statusIsAcceptable && $acceptableStatuses !== null) {
        // Check if status code is in the list of acceptable statuses
        $statusIsAcceptable = in_array($httpCodeInt, $acceptableStatuses);
    }
    
    // Validate status code
    if ($statusIsAcceptable) {
        if ($httpCodeInt === $expectedStatusInt) {
            echo "   ✅ Status: {$httpCode} (expected {$expectedStatus})\n";
        } else {
            echo "   ✅ Status: {$httpCode} (acceptable, expected {$expectedStatus})\n";
        }
        
        // Additional validation if specified
        if (isset($pathConfig['validation'])) {
            $validation = $pathConfig['validation'];
            $content = file_get_contents($tmpFile);
            
            switch ($validation['type']) {
                case 'json':
                    $json = json_decode($content, true);
                    if ($json) {
                        $allFound = true;
                        foreach ($validation['contains'] ?? [] as $key) {
                            if (!isset($json[$key])) {
                                echo "   ⚠️  Missing expected key: {$key}\n";
                                $allFound = false;
                            }
                        }
                        if ($allFound) {
                            echo "   ✅ Validation: JSON contains expected keys\n";
                        }
                    } else {
                        echo "   ⚠️  Response is not valid JSON\n";
                    }
                    break;
                    
                case 'redirect_to_login':
                    $containsLogin = false;
                    foreach ($validation['contains'] ?? [] as $loginIndicator) {
                        if (stripos($content, $loginIndicator) !== false) {
                            $containsLogin = true;
                            break;
                        }
                    }
                    if ($containsLogin) {
                        echo "   ✅ Validation: Redirected to login\n";
                    } else {
                        echo "   ⚠️  Warning: No login indicators found in response\n";
                    }
                    break;
                    
                case 'status_any':
                    // Status code already validated above
                    echo "   ✅ Validation: Status code is acceptable\n";
                    break;
                    
                case 'status_only':
                    // Status code check is sufficient
                    break;
            }
        }
        
        echo "   ✅ PASSED\n\n";
        $passedTests++;
    } elseif ($isUnauthApiTest && $isPermissionFailure) {
        // For unauthenticated API tests, permission failures are expected - warn and continue
        echo "   ⚠️  Status: {$httpCode} (expected {$expectedStatus})\n";
        if ($httpCode === '400') {
            echo "   ⚠️  WARNING: Authentication/CSRF failure ({$httpCode}) - expected for unauthenticated request\n";
        } elseif ($isCreateEndpoint) {
            echo "   ⚠️  WARNING: CREATE endpoint returned {$httpCode} - this is acceptable (may or may not need permissions)\n";
        } else {
            echo "   ⚠️  WARNING: Permission failure ({$httpCode}) - expected for unauthenticated request\n";
        }
        echo "   ⚠️  WARNED (continuing tests to check for code/SQL failures)\n\n";
        $warningTests++;
    } elseif ($isUnauthApiTest && $isServerError) {
        // Server errors indicate actual code/SQL failures - these should fail
        echo "   ❌ Status: {$httpCode} (expected {$expectedStatus})\n";
        echo "   ❌ FAILED: Server error detected - possible code/SQL failure\n";
        
        // Try to read error details from response
        $content = file_get_contents($tmpFile);
        if ($content) {
            $json = json_decode($content, true);
            if ($json && isset($json['message'])) {
                echo "   ❌ Error: {$json['message']}\n";
            }
        }
        echo "\n";
        $failedTests++;
    } else {
        echo "   ❌ Status: {$httpCode} (expected {$expectedStatus})\n";
        echo "   ❌ FAILED\n\n";
        $failedTests++;
    }
    
    // Clean up
    unlink($tmpFile);
}

// Test authenticated paths
if ($authType === 'auth' || $authType === 'both') {
    $authPaths = $config['paths']['authenticated'] ?? [];
    
    // Check if there are any authenticated tests to run
    $hasAuthTests = (
        (($pathType === 'api' || $pathType === 'both') && isset($authPaths['api']) && count($authPaths['api']) > 0) ||
        (($pathType === 'frontend' || $pathType === 'both') && isset($authPaths['frontend']) && count($authPaths['frontend']) > 0)
    );
    
    if ($hasAuthTests) {
        $loginSuccessful = false;
        
        // Try to use Playwright session cookies if available
        if (file_exists($playwrightStateFile)) {
            echo "=========================================\n";
            echo "Using Playwright Session\n";
            echo "=========================================\n";
            echo "Converting Playwright storageState to curl cookies...\n";
            
            if (convertPlaywrightToCurlCookies($playwrightStateFile, $cookieJar)) {
                echo "✅ Playwright session cookies loaded successfully\n";
                echo "   Using authenticated session from previous Playwright login\n\n";
                $loginSuccessful = true;
            } else {
                echo "⚠️  Failed to convert Playwright cookies, falling back to curl login\n\n";
            }
        }
        
        // Fallback: Perform curl-based login if Playwright session not available
        if (!$loginSuccessful) {
            if (!performLogin($baseUrl, $username, $password, $cookieJar)) {
                echo "❌ Authentication failed - skipping authenticated tests\n\n";
                // Count skipped tests
                if (($pathType === 'api' || $pathType === 'both') && isset($authPaths['api'])) {
                    $skippedTests += count($authPaths['api']);
                }
                if (($pathType === 'frontend' || $pathType === 'both') && isset($authPaths['frontend'])) {
                    $skippedTests += count($authPaths['frontend']);
                }
            } else {
                $loginSuccessful = true;
            }
        }
        
        // If login successful (either via Playwright or curl), proceed with authenticated tests
        if ($loginSuccessful) {
            if (($pathType === 'api' || $pathType === 'both') && isset($authPaths['api'])) {
                echo "=========================================\n";
                echo "Testing Authenticated API Paths\n";
                echo "=========================================\n\n";
                
                foreach ($authPaths['api'] as $name => $pathConfig) {
                    testPath($name, $pathConfig, $baseUrl, true, $username, $password, $cookieJar);
                }
            }
            
            if (($pathType === 'frontend' || $pathType === 'both') && isset($authPaths['frontend'])) {
                echo "=========================================\n";
                echo "Testing Authenticated Frontend Paths\n";
                echo "=========================================\n\n";
                
                foreach ($authPaths['frontend'] as $name => $pathConfig) {
                    testPath($name, $pathConfig, $baseUrl, true, $username, $password, $cookieJar);
                }
            }
        }
    }
}

// Test unauthenticated paths
if ($authType === 'unauth' || $authType === 'both') {
    $unauthPaths = $config['paths']['unauthenticated'] ?? [];
    
    if (($pathType === 'api' || $pathType === 'both') && isset($unauthPaths['api'])) {
        echo "=========================================\n";
        echo "Testing Unauthenticated API Paths\n";
        echo "=========================================\n\n";
        
        foreach ($unauthPaths['api'] as $name => $pathConfig) {
            testPath($name, $pathConfig, $baseUrl, false);
        }
    }
    
    if (($pathType === 'frontend' || $pathType === 'both') && isset($unauthPaths['frontend'])) {
        echo "=========================================\n";
        echo "Testing Unauthenticated Frontend Paths\n";
        echo "=========================================\n\n";
        
        foreach ($unauthPaths['frontend'] as $name => $pathConfig) {
            testPath($name, $pathConfig, $baseUrl, false);
        }
    }
}

// Cleanup
if (file_exists($cookieJar)) {
    unlink($cookieJar);
}

// Print summary
echo "=========================================\n";
echo "Test Summary\n";
echo "=========================================\n";
echo "Total tests: {$totalTests}\n";
echo "Passed: {$passedTests}\n";
echo "Warnings: {$warningTests}\n";
echo "Failed: {$failedTests}\n";
echo "Skipped: {$skippedTests}\n";
echo "\n";

// Generate a table format for results (continue on failures - don't fail the test)
$continue_on_failure = getenv('CONTINUE_ON_FAILURE') ?: 'false';
if ($continue_on_failure === 'true') {
    // In report mode, always exit 0 to allow the workflow to continue
    if ($failedTests > 0) {
        echo "⚠️  Some tests failed (actual code/SQL errors detected)\n";
        echo "   Note: Permission failures (400/401/403) are warnings, not failures\n";
        echo "   Continuing workflow to collect all test results...\n";
    } elseif ($warningTests > 0) {
        echo "✅ Tests completed (permission warnings are expected for unauthenticated requests)\n";
        echo "   {$warningTests} permission warnings detected (400/401/403 status codes)\n";
        echo "   No actual code/SQL errors found\n";
    } else {
        echo "✅ All tests passed\n";
    }
    exit(0);
} else {
    // In strict mode, fail on errors
    if ($failedTests > 0) {
        echo "❌ Some tests failed (actual code/SQL errors detected)\n";
        echo "   Note: Permission failures (400/401/403) are warnings, not failures\n";
        exit(1);
    } elseif ($warningTests > 0) {
        echo "✅ All tests passed (permission warnings are expected for unauthenticated requests)\n";
        echo "   {$warningTests} permission warnings detected (400/401/403 status codes)\n";
        echo "   No actual code/SQL errors found\n";
        exit(0);
    } else {
        echo "✅ All tests passed\n";
        exit(0);
    }
}
