// Export all CRUD6 components
export { default as CRUD6ActionModal } from './CRUD6/ActionModal.vue'
export { default as CRUD6ConfirmActionModal } from './CRUD6/ConfirmActionModal.vue'
export { default as CRUD6CreateModal } from './CRUD6/CreateModal.vue'
export { default as CRUD6DeleteModal } from './CRUD6/DeleteModal.vue'
export { default as CRUD6Details } from './CRUD6/Details.vue'
export { default as CRUD6EditModal } from './CRUD6/EditModal.vue'
export { default as CRUD6FieldEditModal } from './CRUD6/FieldEditModal.vue'
export { default as CRUD6Form } from './CRUD6/Form.vue'
export { default as CRUD6Info } from './CRUD6/Info.vue'
export { default as CRUD6DetailGrid } from './CRUD6/DetailGrid.vue'
export { default as CRUD6MasterDetailForm } from './CRUD6/MasterDetailForm.vue'
export { default as CRUD6AutoLookup } from './CRUD6/AutoLookup.vue'
