<?php

/*
 * UserFrosting CRUD6 Sprinkle (http://www.userfrosting.com)
 *
 * @link      https://github.com/ssnukala/sprinkle-crud6
 * @copyright Copyright (c) 2024 Srinivas Nukala
 * @license   https://github.com/ssnukala/sprinkle-crud6/blob/master/LICENSE.md (MIT License)
 */

/**
 * US English message token translations for CRUD6 tests.
 * 
 * AUTO-GENERATED by GenerateSchemas - DO NOT EDIT MANUALLY
 * Generated: {DATE}
 * 
 * These translations are programmatically generated from schema definitions
 * using the SchemaBuilder helper. To update, modify the schemas in
 * app/tests/Testing/GenerateSchemas.php and regenerate.
 */
return array (
  'CRUD6' => 
  array (
    'USERS' => 
    array (
      1 => 'Users',
      2 => 'Userss',
      'PAGE' => 'Userss',
      'PAGE_DESCRIPTION' => 'A listing of users for your site',
      'ID' => 'Id',
      'USER_NAME' => 'User Name',
      'FIRST_NAME' => 'First Name',
      'LAST_NAME' => 'Last Name',
      'EMAIL' => 'Email',
      'PASSWORD' => 'Password',
      'FLAG_ENABLED' => 'Flag Enabled',
      'CREATED_AT' => 'Created At',
      'UPDATED_AT' => 'Updated At',
    ),
    'GROUPS' => 
    array (
      1 => 'Groups',
      2 => 'Groupss',
      'PAGE' => 'Groupss',
      'PAGE_DESCRIPTION' => 'A listing of groups for your site',
      'ID' => 'Id',
      'SLUG' => 'Slug',
      'NAME' => 'Name',
      'DESCRIPTION' => 'Description',
      'ICON' => 'Icon',
      'CREATED_AT' => 'Created At',
      'UPDATED_AT' => 'Updated At',
    ),
    'PRODUCTS' => 
    array (
      1 => 'Products',
      2 => 'Productss',
      'PAGE' => 'Productss',
      'PAGE_DESCRIPTION' => 'A listing of products for your site',
      'ID' => 'Id',
      'SKU' => 'Sku',
      'NAME' => 'Name',
      'DESCRIPTION' => 'Description',
      'PRICE' => 'Price',
      'QUANTITY' => 'Quantity',
      'ACTIVE' => 'Active',
      'CREATED_AT' => 'Created At',
      'UPDATED_AT' => 'Updated At',
    ),
    'ROLES' => 
    array (
      1 => 'Roles',
      2 => 'Roless',
      'PAGE' => 'Roless',
      'PAGE_DESCRIPTION' => 'A listing of roles for your site',
      'ID' => 'Id',
      'SLUG' => 'Slug',
      'NAME' => 'Name',
      'DESCRIPTION' => 'Description',
      'CREATED_AT' => 'Created At',
      'UPDATED_AT' => 'Updated At',
    ),
    'PERMISSIONS' => 
    array (
      1 => 'Permissions',
      2 => 'Permissionss',
      'PAGE' => 'Permissionss',
      'PAGE_DESCRIPTION' => 'A listing of permissions for your site',
      'ID' => 'Id',
      'SLUG' => 'Slug',
      'NAME' => 'Name',
      'DESCRIPTION' => 'Description',
      'CONDITIONS' => 'Conditions',
      'CREATED_AT' => 'Created At',
      'UPDATED_AT' => 'Updated At',
    ),
    'ACTIVITIES' => 
    array (
      1 => 'Activities',
      2 => 'Activitiess',
      'PAGE' => 'Activitiess',
      'PAGE_DESCRIPTION' => 'A listing of activities for your site',
      'ID' => 'Id',
      'USER_ID' => 'User Id',
      'TYPE' => 'Type',
      'OCCURRED_AT' => 'Occurred At',
      'IP_ADDRESS' => 'Ip Address',
      'DESCRIPTION' => 'Description',
    ),
  ),
);
